language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
services:
  - mongodb
install: 
  - npm install -g mocha
  - npm install debug
  - npm install mocha-mongoose
  - npm install mongoose
  - npm install should
  - npm install techjeffharris-utils
before_script:
  - mocha --version