language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
  - mongodb
before_install:
  - sudo apt-get update -qq
install: 
  - npm install -g mocha
  - npm install mongoose
before_script:
  - mocha --version